[tool.poetry]
name = "mopy"
version = "0.1.0"
description = ""
authors = ["MichalOleszak <oleszak.michal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.3"
pytest = "^7.1.1"
black = "^22.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
